### ISSUE TITLE
News Feed

### ISSUE THREAD

**Issue by arturoceballos** [Shift3/ancestreeLiveV3#78]
A user's News Feed should load display:
- [ ] Posts that user has created
- [x] Posts that a user's connection has created
- [ ] Posts that user is tagged in

All of the posts should be arranged in order from the most recent post created to the last.

The News Feed should only load a handful of posts at a time.
- [ ] `Infinite Scroll` in Ionic

**Comment by Basim-Elayan** [comment]
Done
